# Generated by Django 4.1.7 on 2023-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('dsize', models.DecimalField(decimal_places=2, max_digits=4)),
                ('speciality', models.CharField(max_length=30)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('content', models.TextField()),
            ],
        ),
    ]
