# Generated by Django 4.1.7 on 2023-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='allperson',
            name='slug',
            field=models.SlugField(default='watch-post', max_length=100),
        ),
    ]
