# Generated by Django 4.1.7 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_allperson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allperson',
            name='slug',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
