# Generated by Django 4.1.7 on 2023-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_allperson_dsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='allperson',
            name='speciality',
            field=models.CharField(default='Speedy', max_length=30),
        ),
    ]
