# Generated by Django 4.1.7 on 2023-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_allperson_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='allperson',
            name='age',
            field=models.CharField(default='21', max_length=3),
        ),
        migrations.AddField(
            model_name='allperson',
            name='height',
            field=models.CharField(default='5.5', max_length=4),
        ),
    ]
